### ISSUE TITLE
determinedDate

### ISSUE THREAD

**Issue by tkarim** [tkarim/Specify-CU#2]
Move data from ID Date (= text1) to determinedDate field.

**Comment by tkarim** [comment]
Dates that were formatted like 6.10.12 or 7.2.12, etc in the IDDate field/column are not converting right.  8.10.12 becomes 10/12/2008 and it should be 08/10/2012.  

So far these are the problem dates. Will add more as I find them:
6.10.12, 7.2.12, 7.6.12, 7.10.12, 8.2.12, 8.6.12, 5.1.12

Also, there are other dates in this format mm.dd.yy that seems to have converted just fine.

**Comment by jlauters** [comment]
The above dates have been added to the script.

**Comment by tkarim** [comment]
One more.  Some 2005 and 2006 dates are converting to 2015.  I think we had this issue with the cataloged dates too. These are the ones I have found so far in the ID Date conversion.

January 10, 2006 becomes 01/10/2015
March 13, 2006 becomes 03/13/2015
June 30, 2005 becomes 06/30/2015
July 20, 2005 becomes 07/20/2015

**Comment by jlauters** [comment]
Fixed bug in script to opt out of pre date conversion string cleaning. These dates are converting correctly now.
