### ISSUE TITLE
catalogedDate

### ISSUE THREAD

**Issue by tkarim** [tkarim/Specify-CU#3]
Move data from CollDate (= name) field to catalogedDate field.

**Comment by jlauters** [comment]
Jon will create a PHP script to iterate through records in collectionobject table parsing out the string in Name column into a PHP date() and store this result in catalogedDate column

**Comment by tkarim** [comment]
A couple of dates are not converting properly. I don't know if it is an issue on my end or with the converter.  May 1, 2006 becomes 05/01/2015 and May 4, 2004 becomes 05/04/04.  I can try and fix those in Specify so that your converter can deal with them.  It shouldn't take too long.
