### ISSUE TITLE
Type Status data dump

### ISSUE THREAD

**Issue by tkarim** [tkarim/Specify-CU#4]
One more thing when you run the script next Tuesday.  Could you copy all the data from "Type Status" on the determination table into the text2 (now verbatim type status) column?  I need to keep a record of the old entries, but clean up the actual Type Status field for sharing with GBIF, iDigBio, etc.  Thanks!

**Comment by jlauters** [comment]
UPDATE determination set Text2 = TypeStatusName;

**Comment by tkarim** [comment]
looks good.
