### ISSUE TITLE
Websearch update

### ISSUE THREAD

**Issue by tkarim** [tkarim/Specify-CU#5]
New dataset ready for websearch on: /data/web/solr/websearchdata.zip

**Comment by jlauters** [comment]
Which search is this for?

**Comment by tkarim** [comment]
invertpaleosearch.colorado.eduhttp://invertpaleosearch.colorado.edu

On Feb 2, 2015, at 9:24 AM, Jon Lauters notifications@github.com wrote:

Which search is this for?

**Comment by tkarim** [comment]
invertpaleosearch.colorado.edu

**Comment by tkarim** [comment]
Same as above. New data cache added to /data/web/solr/ 

Could you restart solr? Thanks.

**Comment by jlauters** [comment]
data updated and solr restarted.
