### ISSUE TITLE
Check and restart Solr server?

### ISSUE THREAD

**Issue by tkarim** [tkarim/Specify-CU#6]
Just tried to move a new data cache (websearchdata.zip, should be dated today, 5.8.2015) over to /data/web/solr/ and I'm getting a message that there is not such directory. Ideas?

**Comment by jlauters** [comment]
/data/web/solr/ is still there :) last websearchadata.zip is from March 2

**Comment by tkarim** [comment]
weird. Tried it again and it let me move it. New file should be  there now.

**Comment by jlauters** [comment]
great. I'll update :)

**Comment by tkarim** [comment]
super! Thanks!

**Comment by jlauters** [comment]
Data updated and solr restarted. Let me know if everything looks good.

**Comment by tkarim** [comment]
looks good. Thanks!
