### ISSUE TITLE
Restart solr and teach me how?

### ISSUE THREAD

**Issue by tkarim** [tkarim/Specify-CU#7]
Hi... could you restart the solr server and possibly when you get back show me how to do it so I don't have to bug you all the time? :) Thanks!

**Comment by jlauters** [comment]
You may have to contact OIT to get sudo access on your user for this.

```
sudo /sbin/service solr stop
unzip /data/web/solr/websearchdata.zip
cd /data/web/solr/cumuseum/collection1/data
mv index index.bak
mkdir index
cd index
cp -R /data/web/solr/PortalFiles/solr/* .
sudo /sbin/service solr start
```

-- update portalInstance number
-- update fldmodel.json
-- update schema

**Comment by jlauters** [comment]
Solr has been restarted.

**Comment by tkarim** [comment]
Thanks. Yeah, I figured I would need to get access too. Thank you!

**Comment by tkarim** [comment]
Data there. Looks good. Thanks.
